### ISSUE TITLE
Fail to minify within Docker node:10-alpine

### ISSUE THREAD

**Issue by luis02lopez** [SupremeTechnopriest/react-idle-timer#123]
Hi guys, first of all, thank you for having this package!

We've found some errors compiling our app with the following context:

- Docker base image from node:10-alpine (Node 10.22)
- package.json semantic version as: `"react-idle-timer": "^4.2.9"`

Throw the following error on` npm run build`:

```
Failed to minify the code from this file: 

 	./node_modules/react-idle-timer/dist/index.es.js:1:344
```

Going to the build log, this can be seen:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.6
3 info using node@v10.22.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle borrower-react@0.1.0~prebuild: borrower-react@0.1.0
6 info lifecycle borrower-react@0.1.0~build: borrower-react@0.1.0
7 verbose lifecycle borrower-react@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle borrower-react@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle borrower-react@0.1.0~build: CWD: /usr/src/app
10 silly lifecycle borrower-react@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
11 silly lifecycle borrower-react@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle borrower-react@0.1.0~build: Failed to exec build script
13 verbose stack Error: borrower-react@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid borrower-react@0.1.0
15 verbose cwd /usr/src/app
16 verbose Linux 4.19.76-linuxkit
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.22.0
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error borrower-react@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the borrower-react@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Checking dependencies, this can be seen (npm list ):

```
npm ERR! peer dep missing: redux@^3.1.0, required by redux-devtools-extension@2.13.2
npm ERR! peer dep missing: redux@^3.0.0, required by redux-form@7.3.0
npm ERR! missing: react-input-mask@^2.0.4, required by borrower-react@0.1.0
npm ERR! missing: react-idle-timer@^4.2.9, required by borrower-react@0.1.0
npm ERR! missing: react-otp-input@^1.0.1, required by borrower-react@0.1.0
npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.2.0
```

What we had to do is a downgrade from using 4.3 to 4.2 of your package and started to work. Cheers!

**Comment by SupremeTechnopriest** [comment]
Hello!  What are you using to minify your project?  Uglify doesn't work with es6 modules out of the box.  I think that might be what you are seeing here.  I recommend switching to [terser](https://www.npmjs.com/package/terser).  If you are using webpack you can use this [plugin](https://www.npmjs.com/package/terser-webpack-plugin) or for rollup use this [plugin](https://www.npmjs.com/package/rollup-plugin-terser).

Let me know if this fixes your issue!

**Comment by rhiadj** [comment]
@SupremeTechnopriest hey there! First off thanks for an awesome module and for the great work maintaining this and being so responsive to issues raised.

This issue tripped up my project today also.

Absolutely take your point here and I'm sure we can have a look into moving our build pipeline to using terser to work with newer versions of `react-idle-timer`. Right now though we've got some super urgent requirements we need to get live in the next week and this just caused quite a bit of head scratching as our branch builds were failing due to this issue.

Is there any way at all you'd be able to get this module to be compatible with Uglify again? Playing devil's advocate, we have thousands of dependencies and none of them cause our build to fail/rely on a specific minifier being used. Also, given previous patch versions of this module built fine using Uglify it kind of feels a little like a breaking change for this now not not to - which kind of goes against node minor versions?

I imagine there's quite a few builds that might start failing when people start to pull in latest versions of this - and for all of those dependency trees to have to switch to using terser does feel like quite a bit of collective effort - esp given how massively popular this module is! 🥰 

More than happy to go with your judgement on this but figured I'd mention for the record that this little niggle has tripped up at least one other project (ours).

Thanks again for all your hard work - very much appreciated!

**Comment by SupremeTechnopriest** [comment]
@rhiadj Sure I'll see what I can do.  Can you tell me what version of `create-react-app` you are running?  I'll need to be able to recreate the issue in order to fix it.  It looks like the version of uglify they are using doesn't know about the `let` keyword.  That's what it's failing to minify on column `1:344`. I've tested it with the latest version of `create-react-app` and it minifies ok, must be an issue with earlier versions not being able to minify let.  

Come to think of it... I used to transpile the component with babel.  That's probably why this popped up.  I removed the babel transpilation because everything I was using is now standard. Willing to bet the `let`s were transpiled to `var`s....

Yup just confirmed.  Let me whip up a patch for you.  Stand by.

**Comment by SupremeTechnopriest** [comment]
@rhiadj @luis02lopez Hey all.  I patched this regression and published to NPM as version `4.3.5`.  Please re install and let me know how it goes.

**Comment by rhiadj** [comment]
Wow that's amazing thank you so much @SupremeTechnopriest - you are an absolute legend! 👍 

Keep up the great work! 👏 🙇

**Comment by luis02lopez** [comment]
It compiles now! thank you so much!! @SupremeTechnopriest cheers 🍻
