### ISSUE TITLE
useIdleTimer reinitialization after api request

### ISSUE THREAD

**Issue by Talhafayyaz11** [SupremeTechnopriest/react-idle-timer#128]
First of all thanks for this amazing package. In my scenario, I want to handle the timeout from the state. And whenever that state updates I want to reinitiate my timer according to the given value. Basically, I am getting the timeout value from the backend and I want to reinitialize my timeout value according to the value I get. I have read the reset API but it does not complete my requirement because I want to reinitialize the timeout value not reset it. I would be really thankful for your help thanks in advance.

**Comment by SupremeTechnopriest** [comment]
Hi @Talhafayyaz11.  Are you using the hook or the component?

**Comment by SupremeTechnopriest** [comment]
Ah its in the title.  My bad.  Im not sure if that will be possible with the current hook implementation, though it is possible with the component implementation.  Pretty sure I can add support for that in the hook.  I will add some tests later today and get back to you.

**Comment by SupremeTechnopriest** [comment]
@Talhafayyaz11 So I wrote a test that I think encompasses your needs:

```js
   it('Should allow timeout to be changed dynamically', done => {
        props.onIdle = sinon.spy()
        props.timeout = 500
        const { result, rerender } = idleTimer()
        setTimeout(() => {
          expect(props.onIdle.callCount).toBe(1)
          props.timeout = 300
          rerender()
          result.current.reset()
          setTimeout(() => {
            expect(props.onIdle.callCount).toBe(2)
            done()
          }, 400)
        }, 600)
      })
```

This tests passes with no changes to the `useIdleTimer` hook.  You just need to call `reset()` after you set your new timeout value so the internal timeouts are recreated with the new value. 

Correct me if Im wrong, but what you wanted to do is set the new timeout value without starting the timer back from 0?  That would be tricky to implement, but you can probably get it done with `getRemainingTime()`.  If the remaining time is less than your new `timeout` value, then the user is idle.  Otherwise you can just update the timeout and call `reset` on the idleTimer hook.  I think it's pretty safe to assume that if you just completed a rest operation that the user is active and manually resetting the timer would be ok. 

Let me know if this helps!

**Comment by Talhafayyaz11** [comment]
Thanks @SupremeTechnopriest.

**Comment by SupremeTechnopriest** [comment]
Any time!
