### ISSUE TITLE
Ability to keep IdleTimer on even in the sleep mode.

### ISSUE THREAD

**Issue by dollychhabriya** [SupremeTechnopriest/react-idle-timer#138]
Is there a way through which we can keep Idle timer on even when the laptop is in sleep mode?

**Comment by SupremeTechnopriest** [comment]
As IdleTimer is timeout based, not in its current implementation.  I can think about ways to add this functionality.  One idea is grabbing a timestamp on the `pagehide` event and grabbing another on the `pageshow` event.  If the diff is greater than the timeout value, fire onIdle.  Im not sure if the events are fired on system sleep.  Its something I would have to test.

**Comment by SupremeTechnopriest** [comment]
@dollychhabriya Since sleep mode is an OS level feature, I don't think there is much that can be done to support your feature request. I tested a few implementations, but it turned out to be redundant. The best that we can do is when the user wakes up the computer, the idle event should fire.  You might want to think about passing your own list of events as the default event list includes `visibilitychange`.
