### ISSUE TITLE
how can i write test cases for this i am trying but getting errors

### ISSUE THREAD

**Issue by mehuljariwala** [SupremeTechnopriest/react-idle-timer#142]
can someone please help me with test cases in React TSX.

**Comment by mehuljariwala** [comment]
Need examples of test cases that would easy to understand

**Comment by SupremeTechnopriest** [comment]
This package has close to 100% test coverage.  You don't really need to test it because all the code is already covered... That said, you can take a look at the tests [here](https://github.com/SupremeTechnopriest/react-idle-timer/tree/master/src/__tests__) and it should get you started.  If your questions are specific to Typescript it would be better to ask in stack overflow.  I am not a fan of typescript for a lot of reasons.  I maintain the `.d.ts` file by hand.
