### ISSUE TITLE
Need support for  crosstab trigger action

### ISSUE THREAD

**Issue by lengockyquang** [SupremeTechnopriest/react-idle-timer#160]
Are there any option for crosstab action, to make sure that all tabs are not going to idle state if a tab is still active. ??
For example, I have 3 tabs such as tab A, B and C. A is the leader then user duplicate tab B and C from A, so tab B and C is not the leader tab. If we can make tab A or B or C is still active (action is trigger frequently) so other tabs are not going to idle state.

With image below, when i triggered action on leader tab, its idle state became false and the last event is Active. But with other tab, the idle state was still persist. I using crosstab emitter on all tabs with component example.
![image](https://user-images.githubusercontent.com/45225905/117687622-2bc52e00-b1e2-11eb-9b3e-7685e64757cd.png)

**Comment by SupremeTechnopriest** [comment]
Hello @lengockyquang,  Action is currently not supported on the cross tab manager. Only `onActive` and `onIdle` are replicated across tab.  The reasoning behind this was two fold.  Firstly, I didn't want to saturate the message layer with onAction events.  Especially since the localStorage fallback method is blocking.  Secondly I couldn't think of a good reason why you would want this. Really, you would want activity events to only be fired on the tab the user is active on.  

That said,  what you are trying to achieve works out of the box with the `onIdle` and `onActive` events.  As long as a user is active on one tab (leader or not) all the other tabs will remain active.  It's not until all tabs become idle that the `onIdle` event is emitted.  If you run in `emitOnAllTabs` mode, the events will be fired on all tabs.  Otherwise just the leader tab will emit the events.
