### ISSUE TITLE
useIdleTimer memoization 

### ISSUE THREAD

**Issue by luxplanjay** [SupremeTechnopriest/react-idle-timer#176]
Hi, great work you are doing. Many thx 👏.

Public API methods like `getTotalActiveTime` and such need to be memoized on your end. Right there is source code. https://github.com/SupremeTechnopriest/react-idle-timer/blob/114f4640e951622184af0307843c58afbed4cb73/src/useIdleTimer.js#L299

Otherwise when used in deps array of useEffect, useMemo or other hook with deps, it causes render loop. Your example disables `react-hooks/exhaustive-deps` eslint rule, which is not an option on a production level project and breaks «react way» of doing things. I can submit a PR with quick fix if you don't have spare time.

PS: I don't see any available labels, so can't mark this as an enhancement.

**Comment by SupremeTechnopriest** [comment]
Hey @luxplanjay,

If you wouldn't mind submitting a PR that would be great.  I am in the middle of releasing a new product and wont have time to work on this until early Q4.  As far as the eslint exclusion in the examples, you don't need to do that in a production app.  Its only because I'm importing the local copy of react-idle-timer which resides outside of the example package's root.  This allows me to test changes by hand without having to publish a new version.

Looking forward to reviewing your PR!

**Comment by SupremeTechnopriest** [comment]
Hey @luxplanjay,

The version 5 beta is now out and can be installed with `npm i react-idle-timer@next`.  All methods and callbacks are now memoized.  You can check out the docs at [https://idletimer.dev](https://idletimer.dev).  Im going to close this issue, but if you have any additional problems or concerns, feel free to open another one.
