### ISSUE TITLE
Testing onAction with useIdleTimer hook in Enzyme

### ISSUE THREAD

**Issue by SVaeth** [SupremeTechnopriest/react-idle-timer#179]
We are trying to write a test for our health check module that uses this library.The issue we are running into is the onAction is not firing for a simulated mouse event with enzyme.

The code:

```js
import React from "react";
import { mount, configure } from "enzyme";
import { act } from "@testing-library/react";
import TimerPanel from "./TimerPanel";
import Adapter from "enzyme-adapter-react-16";

describe("Testing onAction", () => {
  configure({ adapter: new Adapter() });

  it("should make modal disappear when mouse event has happened", async () => {
    const actionMock = jest.fn();
    const wrapper = mount(<TimerPanel timeout={30000} onAction={actionMock} />);
    expect(actionMock).not.toBeCalled();

    await new Promise((resolve) => setTimeout(resolve, 300));

    act(() => {
      wrapper.simulate("mousedown");
    });
    wrapper.update();

    expect(actionMock).toBeCalledTimes(1);
  });
});

```

Sandbox:

https://codesandbox.io/embed/react-idle-timer-with-hook-forked-s4tq2?fontsize=14&hidenavigation=1&theme=dark

I looked at the code here in the tests for react-idle-timer for ideas, but it isn't working with enzyme

```js
it('Should call onAction on user input when user is not idle', async () => {
        props.onAction = jest.fn()
        props.timeout = 400
        props.debounce = 0
        idleTimer()
        await sleep(300)
        simulant.fire(document, 'mousedown')
        expect(props.onAction.mock.calls.length).toBe(1)
      })
```

Unfortunately simulant did not work either (simulant is not an option for us either, it is not in our npm registry)

**Comment by SupremeTechnopriest** [comment]
Thats an interesting bug... Could you possibly create a codesandbox so I can see whats going on?  What happens if you remove the `act` wrapping function?  Is there a reason why you are using both testing-library and enzyme?  Why not just use testing-library to render as well? 

I just finished version 5 of idle timer and I dropped enzyme in favor of testing-library.  Enzyme has no official support for react 17.  If you decide to upgrade you will definitely want to take a look at [testing considerations](https://idletimer.dev/docs/getting-started/testing) from the docs. 

Version 4 uses enzyme for all its tests and everything fires just fine.  I have a feeling it might have to do with mixing simulate with act.  Let me know what you come up with and if you get me that sandbox I can help you debug.  You might want to consider [stackblitz](https://stackblitz.com/) as it gives you a terminal that you can run your tests in.

**Comment by SupremeTechnopriest** [comment]
Hey @SVaeth 

This issue has been waiting for a response for over two weeks.  I am going to close it for now, but if you get back to it and still need help, feel free to reopen.
