### ISSUE TITLE
Page Visibility State changes should pause() and resume() timers.

### ISSUE THREAD

**Issue by susylPearl** [SupremeTechnopriest/react-idle-timer#265]
I want to pause the idleTimer when i move to different window or tabs from current timer implemented tab and again when i switch back to previous tab, i want the timer to resume from last active time.

Example:
- when i am on idleTimer tab (A), the total active time was 10 seconds.
- i go to another tab (B) , here another tab means not idleTimer implemented tab, its totally different site/page, and roam around there for 20 seconds.
- i came back to previous tab (A), now i want my idleTimer getTotalActiveTIme() starts from 10 seconds, not from 30 seconds.
is it possible?

I have used code like this:

       `document.addEventListener('visibilitychange', () => {
            if (document.visibilityState === 'visible') {
                this.idleTimer.resume();
                
                console.log('tab is resumed');
            } else {
                this.idleTimer.pause();
                
                console.log('tab is paused');
            }
        });`

**Comment by SupremeTechnopriest** [comment]
Hey there.  This is not something I would be able to add to the library by default.  Most people use `IdleTimer` for security purposes and would want to continue the timer if the page is backgrounded.  However, this is something that you can easily implement yourself.  You are half way there with your code snippet.  You just need to omitthe `visibilitychange` event from the events prop.  Here is an example:

> This assumes you are using v5

```js
import { useIdleTimer, DEFAULT_EVENTS } from 'react-idle-timer'

const events = [...DEFAULT_EVENTS]
events.slice(events.indexOf('visibilitychange'), 1)

const App = () => {
  const idleTimer = useIdleTimer({
    ...yourOtherProps,
    // You can also just supply your own array of events to listen on
    // rather than cloning and mutating the DEFAULT_EVENTS
    events
  })

  useEffect(() => {
    const changeHandler = () => {
      if (document.visibilityState === 'visible') {
        idleTimer.resume()
      } else {
        idleTimer.pause()
      }
    }
    window.addEventListener('visibilitychange', changeHandler)
    return () => {
      window.removeEventListener('visibilitychange', changeHandler)
    }
  }, [])
}
```

The reason why you your `visibiltychange` was triggering the timer is because its part of the [DEFAULT_EVENTS](https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/utils/defaults.ts#L27) array.  Omitting it will solve your problem.

**Comment by SupremeTechnopriest** [comment]
Feel free to reopen this if it does not solve your use case.
