### ISSUE TITLE
console warning

### ISSUE THREAD

**Issue by benmonro** [SupremeTechnopriest/react-idle-timer#5]
when I navigate away from a page w/ an idle timer on it, i get the following error:

``` Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.```

**Comment by fkrauthan** [comment]
I've seen a similar issue already. Looks like it only happens with a very long timeout. As soon as I reduce the timeout to a couple of seconds everything is fine.

**Comment by SupremeTechnopriest** [comment]
Thanks for reporting.  I believe I know how to resolve this issue.  I will take a look soon.

**Comment by benmonro** [comment]
:+1:

**Comment by SupremeTechnopriest** [comment]
I think this was happening because I wasn't clearing the interval on `componentWillUnmount` version `1.2.10` should resolve that.  Published to npm if you want to confirm.  If you still see this issue please reopen.

**Comment by abelovic** [comment]
I get this error as well (current version 1.3.2). Has anyone found a fix for this? It looks like the event listeners are not getting removed on unmounting :/

**Comment by abelovic** [comment]
I get this error as well (current version 1.3.2). Has anyone found a fix for this? It looks like the event listeners are not getting removed on unmounting :/

**Comment by SupremeTechnopriest** [comment]
https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/index.js lines 58-63 show the un-mounting. pretty sure this issue is resolved.  Can you provide a stack trace?  Also what version of React are you using?

**Comment by SupremeTechnopriest** [comment]
https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/index.js lines 58-63 show the un-mounting. pretty sure this issue is resolved.  Can you provide a stack trace?  Also what version of React are you using?

**Comment by SupremeTechnopriest** [comment]
https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/index.js lines 58-63 show the un-mounting. pretty sure this issue is resolved.  Can you provide a stack trace?  Also what version of React are you using?

**Comment by SupremeTechnopriest** [comment]
https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/index.js lines 58-63 show the un-mounting. pretty sure this issue is resolved.  Can you provide a stack trace?  Also what version of React are you using?

**Comment by SupremeTechnopriest** [comment]
https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/src/index.js lines 58-63 show the un-mounting. pretty sure this issue is resolved.  Can you provide a stack trace?  Also what version of React are you using?

**Comment by SupremeTechnopriest** [comment]
sorry about that spam.  looks like github is broken.

**Comment by abelovic** [comment]
React 15.2.0

ReactUpdateQueue.js:49 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the IdleTimer component.

printWarning (warning.js:42)
warning (warning.js:60)
getInternalInstanceReadyForUpdate (ReactUpdateQueue.js:49)
enqueueSetState (ReactUpdateQueue.js:201)
ReactComponent.setState (ReactComponent.js:64)
_handleEvent (index.js:145)
wrapper (index.js:245)

As @benmonro stated it happens when I navigate away (secure to unsecure page for instance) in which case the component is unmounted. It appears to still run the _handleEvent method (I wrote to the console to verify that the event is still triggered) even though it does appear as if you are removing the event listeners (line #62). 

Any ideas?

**Comment by abelovic** [comment]
No worries :) Thanks for your quick response!
