### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by BenevidesLecontes** [SupremeTechnopriest/react-idle-timer#54]
Hi, thank you for your great work, I'm trying to use this library in my App, but it seems that `onActive` and `onIdle` are triggered only one time. Tried use your example, but no success, the same thing happens. The odd thing is, if I do `new Date().getTime()` and pass to the component as `timeout`, all the mentioned callbacks are triggered, but if i do `1000 * 60 * 40` and pass the result as `timeout don't`. Can you help with this one?

**Comment by SupremeTechnopriest** [comment]
Can you post some code for me to look at or link me to a repo?

**Comment by SupremeTechnopriest** [comment]
So rendering your children through IdleTimer requires careful thought. You can end up with inadvertent state spam if you dont utilize `shouldUpdateComponent` properly.  Im thinking about removing support for it.  Can you try to change your render block to:

```
render() {
    return (
      <div>
        <IdleTimer
          ref={ref => { this.idleTimer = ref; }}
          element={document}
          onActive={this.onActive}
          onIdle={this.onIdle}
          timeout={this.state.expireTime} />
          {this.props.children}
        <div>
    );
  }
```

I also noticed you're using state to populate the timeout property.  If your state changes (user wants to change their idle time interval) you probably want to reset the timer `this.idleTimer.reset()` after you change your state.... I wouldn't recommend using state here.  Props are probably better if you can.

**Comment by BenevidesLecontes** [comment]
@SupremeTechnopriest I did the changes, but i got the same results.

**Comment by SupremeTechnopriest** [comment]
What does `expireTime` log out to?

**Comment by SupremeTechnopriest** [comment]
I see what you are trying to do here, and this isn't really what IdleTimer is designed for.  You want to log out your user when their token expires.  You should really implement this as a middleware to your fetch calls that are authenticated.  For example:

You fetch an authenticated route with your token.  Token is bad you send a 401.  On client side you catch the 401 and log out your user.  

IdleTimer is more for when you want to say "If my user walks away from their keyboard for 5 minutes, prompt them with a modal for 10 seconds.  If no action log them out".  JWTs typically expire in days or weeks after they are issued.  You wouldn't want to set a client side timer for that long.  Most of the time you wouldn't need to because that browser session would never come close to triggering the timeout.  Just causes excess overhead.  

Does that make sense?

**Comment by BenevidesLecontes** [comment]
@SupremeTechnopriest  my token expire in 15 minutes. So what I'm trying to do is basically what you said about IdleTimer design.

**Comment by SupremeTechnopriest** [comment]
I see.  Would you mind capturing a log so we can just rule that out?

**Comment by SupremeTechnopriest** [comment]
Yeah, sure.  Anything to go on.  I cant imagine the events not working unless the configuration is off.

**Comment by BenevidesLecontes** [comment]
@SupremeTechnopriest here's the gif
![2018-09-19 20 05 19](https://user-images.githubusercontent.com/1839361/45786708-1d4c3180-bc48-11e8-8d31-6116e3abfbd4.gif)

**Comment by SupremeTechnopriest** [comment]
Ok thanks for that.  Input looks ok. So after this you waited the full 15 mins idle (no user input) and the function wasn't called?

**Comment by SupremeTechnopriest** [comment]
Remember that every time you get user input it resets your timer.  Maybe you want to set the events prop to `[]` so you arent listening on any events.  Then the timer will fire in 15 minutes no matter what.

**Comment by SupremeTechnopriest** [comment]
Currently you're telling idle timer that its okay to receive no user input for 15 minutes before the user is considered idle.  Thats not what you want.

**Comment by BenevidesLecontes** [comment]
@SupremeTechnopriest thank you, for your time, I ended up doing what you said and is working.

**Comment by SupremeTechnopriest** [comment]
Sure no problem.  Good luck on your project. Thanks for using IdleTimer :)
