### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getRemainingTime' of null at eval

### ISSUE THREAD

**Issue by surendragalwa111** [SupremeTechnopriest/react-idle-timer#80]
Code is:-
```
constructor(props) {
    super(props);
    this.idleTimer = null;
    this.state = {
      remaining: null,
      isIdle: false,
      lastActive: null,
      elapsed: null,
    };
  }

componentDidMount() {
    this.setState({
      remaining: this.idleTimer.getRemainingTime(),
      lastActive: new Date(this.idleTimer.getLastActiveTime()),
      elapsed: this.idleTimer.getElapsedTime(),
    });

    setInterval(() => {
      this.setState({
        remaining: this.idleTimer.getRemainingTime(),
        lastActive: new Date(this.idleTimer.getLastActiveTime()),
        elapsed: this.idleTimer.getElapsedTime(),
      });
    }, 1000);
  }
```
After every second when it updates the state, it throw the underlying warning:-
**Uncaught TypeError: Cannot read property 'getRemainingTime' of null at eval**

### Issue2:-
onAction is getting called multiple times for a single event.

**Comment by SupremeTechnopriest** [comment]
Can I ask why you are setting this interval? Idle timer has its own timer and keeps its internal variables up to date. The can't reaz property error is likely due to a scope problem but I wouldn't be able to tell without seeing the whole file. I can be certain that this is not a big with IdleTimer, but R at her with your implementation.

**Comment by surendragalwa111** [comment]
Ah, this make sense. Idle timer updates timer internally. :)
