### ISSUE TITLE
react native support?

### ISSUE THREAD

**Issue by ericraio** [SupremeTechnopriest/react-idle-timer#9]
Does this library work for react native? If so, can I update the docs?

**Comment by SupremeTechnopriest** [comment]
In theory it should work with react-native with minimal adjustments. I can add support over the weekend.

**Comment by SupremeTechnopriest** [comment]
So I looked into this, and as it turns out, the activity I would need to record for mobile is different then desktop.  It would end up being its own module.  

Thinking about the use cases I can't really come up with a scenario where you would want to use this on a mobile app. When a user backgrounds the application you can assume they are idle.  

If enough people :+1: this issue ill make a port for `react-native` otherwise it will be a wontfix.
