### ISSUE TITLE
onIdle is immediately called when using large value for timeout

### ISSUE THREAD

**Issue by marina-h** [SupremeTechnopriest/react-idle-timer#92]
Hi, I'm having an issue where `onIdle` is immediately called when the `timeout` value is set to certain large numbers such as 50000000000 (but not 10000000000).

**To reproduce:**
In the example `App.js`, change the timeout state to `50000000000` from `3000`.

**Comment by SupremeTechnopriest** [comment]
For some reason I haven't been receiving emails for new issues?!  Sorry for the delay.  I'll take a look at this after work today.

**Comment by SupremeTechnopriest** [comment]
Hey @marina-h, 

So the issue here is because the number `50000000000` does not fit in a 32 bit integer.  It also equates to a really long time. It's roughly a year and a half.  The largest timeout you can set is `2147483647`.  Even that is pretty large for this library.  It's about 25 days.  This library is more for short lived timeouts.  I would say 15 - 30 mins max.  The browser turns off timers when the website is background and weird stuff happens with long running timers.  

If you need a long timer I suggest using a JWT and setting the expiration to what ever you need.  JWT is built for longer sessions. 

Hope this helps!

**Comment by marina-h** [comment]
Thanks for the update and explanation!
